### ISSUE TITLE
TCGI Code Access and Implementation

### ISSUE THREAD

**Issue by benjaminb115** [cl3225/CHAZ#1]
I’m currently working through the CHAZ model tutorial and noticed that the tutorial uses precomputed TCGI (Tropical Cyclone Genesis Index) datasets for a specific year (2017). However, I’d like to calculate TCGI for other years and scenarios to align with my project requirements.

Is there an official repository, documentation, or an anticipated release date for the TCGI calculation code?

**Comment by cl3225** [comment]
Not yet. TCGI is the only part that was not written in python. My student is working on TCGI repository and will release it after publishing her work.  You can use other GPI indices to get you the probability of the genesis rate in time and space. 
--
Chia-Ying Lee
Lamont Associate Research Professor, Lamont-Doherty Earth Observatory
Columbia University
