### ISSUE TITLE
ERA-5 data SFTP & recent changes of time array to valid_time.

### ISSUE THREAD

**Issue by alexandrefierro** [cl3225/CHAZ#2]
Greetings:

Given the excruciating slowness & clunkiness of the CDS ERA-5 server, would you be able to provide a public SFTP for me (users) to retrieve all the required input ERA-5 data for all the years you may already have in hand (e.g., those used in your papers for reproducibility purpose)? This would be extremely useful.

Also, users have recently been experiencing issues with another similar CU synthetic model (from Lin et al.) due to changes in  ERA-5 nomenclature of the time array to "valid_time". Has this been addressed in this release?

Last, it wasn't clear from the documentation what these files are/mean and how they are created:
pre/TCGI_CRH_PI_1981.mat  etc ..
PI/PI_2001.mat ...
Could you please elaborate on that? 

Thank you,

**Comment by mandli** [comment]
ERA-5 data technically is not really supposed to be distributed outside of the channels that are available already without explicit [licensing](https://www.ecmwf.int/en/forecasts/accessing-forecasts/licences-available).  That being said, you can probably ask for the data used directly via email.

The other two issues I would create two separate GitHub issues for so they can be addressed individually and discussed.

**Comment by alexandrefierro** [comment]
Hi Mandli: I did make a separate request by email to <cl3225@columbia.edu> but haven't heard back yet (likely because of Thanksgiving as I am in Europe). I will open separate GIT queries for my other questions if this is what you prefer ...

**Comment by mandli** [comment]
Thanks @alexandrefierro!

**Comment by mandli** [comment]
This issue is replaced by #3 and #4.
