### ISSUE TITLE
Explanation/background on what TCGI_CRH_PI_YYYY.mat and PI_YYYY.mat are

### ISSUE THREAD

**Issue by alexandrefierro** [cl3225/CHAZ#3]
Hi Mandi et al.:

Here is query number 3 as a separate GIT issue:

(iii) Last, it wasn't clear from the documentation what these files are/mean and how they are created:

pre/TCGI_CRH_PI_YYYY.mat  ..
PI/PI_YYYY.mat ...

Could you please elaborate on that?

Thanks

**Comment by cl3225** [comment]
These are default file names, YYYY means year in 4 digits, such as 2019, 2020.  Both files will be created by users. PI can use calculated using https://github.com/dgilford/tcpyPI, and TCGI is an equation follow Tippett et al. 2011.

**Comment by alexandrefierro** [comment]
Thank you Chia-Ying. This helps; thank you. My original question was more along the lines of: Are all these PI-related *mat files required during the pre-processing steps to run CHAZ and produce synthetic TC track data files? This wasn't very clear to me in the documentation. Thanks again!

**Comment by cl3225** [comment]
No, these are separated from pre-process code. CHAZ read in these files and the preprocess generates the required input data.
--
Chia-Ying Lee
Lamont Associate Research Professor, Lamont-Doherty Earth Observatory
Columbia University

**Comment by alexandrefierro** [comment]
When you state "CHAZ read in these files"; does this imply that these *mat files are mandatory to run the actual CHAZ model or are these *mat files just used for post processing/model verification ? Thanks again for your help & clarifications.

**Comment by alexandrefierro** [comment]
Hi Chia-Ying: Wondering if you received my questions above? Thank you for any help you are able to provide.

**Comment by cl3225** [comment]
This are mandatory field for running the genesis component of the CHAZ model. it is not part of the preprocess code but it is pessary. Again, you can generate your genesis probability using other methods.

**Comment by alexandrefierro** [comment]
Hi Chia-Ying: I don't know exactly why the issue is being closed as I havent confirmed that it is resolved on my end. I know Susan and Michael & met them many times during my 20+ year academic track in the US so perhaps I could contact them directly if you are unable to help with this?.  I am still struggling with the documentation as information seems to be scattered all over the place. The PI *mat files seem to be read by the src/preprocess.py so are they needed to run the model and, if yes, how can user create them? Do you have the Matlab code that does so as I'd need to create files for years 1969-2020 (only 2000, 2001, 2002 are available in the example)? Thank you.

**Comment by mandli** [comment]
While it was perhaps premature to close the issue, it reads to me that the question was answered, but how to generate the input files you mentioned was not.  If I recall correctly (@cl3225 correct me if I am wrong) Susana Camargo does have a code that can generate these files, but that code is not included in CHAZ.  As @cl3225 mentioned though, there are multiple ways to generate the genesis input files beyond what Suzana does.

**Comment by alexandrefierro** [comment]
Hi Mandli: This is clear. Would you thus mind providing the PI .mat files for all years you have available to date (1981-2023 being preferred) and the Matlab source code(s) to generate these? I am sure that there exists multiple alternatives to generate these PI files for those actively working in this field of research - however it is sensible to realize that some users (like myself) not focusing on this field would greatly benefit from all available software to start building their own. I have released (Fortran) codes back in the day (via Sourceforge/Mercurial well before the advent of GIT) for WRF, which are still used today - all pre-processing software were included even though most programmers could likely code these themselves (especially since the advent of AI tools such as ChatGPT). For sharing the PI .mat files & Matlab code(s), could you please use my non-work email address: alexandre.o.fierro@gmail.com. Cheers and thank you.

**Comment by mandli** [comment]
I do not have the code nor the data files.  I would directly contact Suzana Camargo for at least the latter.

**Comment by alexandrefierro** [comment]
OK. I'll email Suzana. Running a synthetic model based on 3 years (2000-2002) of input data is moot as the sample size will be largely insufficient to resolve the tail of the distribution (extremes). I'd suggest the developers to include all the necessary files to run/use this model as intended and/or - to the least - the source code used to generate all necessary input files (for the aforementioned reasons & for reproducibility purposes as underlined in data management plans when submitting a manuscript for peer review). Cheers, thanks & case now closed.

**Comment by mandli** [comment]
Agreed that this is not enough to do much of anything meaningful beyond confirm that the pipeline works.  I would agree that it would be nice to have everything in a workflow under one repository but that is rarely possible today.  The one area we could improve upon is ensuring there is an open version of each part of that chain.  Something to discuss.
