### ISSUE TITLE
Namelist: meaning of "ignore variables when run XYZ is False" + GoM recommendations

### ISSUE THREAD

**Issue by alexandrefierro** [cl3225/CHAZ#4]
Hi Mandi eet al:

Last query as a separate GIT issue:

For the CHAZ and Preprocess Run blocks in the namelist, could you please elaborate on what "ignore variables when run XYZ is False" mean in each block [along with any recommendations for the most appropriate flags to use in these 2 blocks for the Gulf of Mexico]?

Cheers and thanks,

**Comment by cl3225** [comment]
means if the first flag is set to False, the follow up flags is not used.

**Comment by alexandrefierro** [comment]
Thank you & noted.
The second part of my question has not been addressed yet, however: What would be your recommendation to properly run CHAZ for eg the Gulf of Mexico? Set all these flags to True or a subset of it? Thank you!

**Comment by cl3225** [comment]
In the CHAZ.py, after "climInitDate, climInitLon, climInitLat = GBP.getSeeding(fpath,iy,EXP,ratio)” you can set a statement to use only the initial genesis locations (climInitLon, climInitLat ) in the GoM 
--
Chia-Ying Lee
Lamont Associate Research Professor, Lamont-Doherty Earth Observatory
Columbia University

**Comment by alexandrefierro** [comment]
I am afraid being slightly confused by the above as my question was only related to the setup of the namelist flags, namely:

calWind = True 
calpreProcess = True 
calA = True

and:

### genesis 
calGen = True 
### track
calBam = True
### intensiy
calInt = True

Would you recommend them being all set to True to generate 10K-100K+ years equivalent of track data (for an extreme value probabilistic analysis) in the GoM (or elsewhere). Thank you.
